### PR TITLE
Add react-app-rewire-svg-react-loader

### PR DESCRIPTION
**Pull request by lnhrdt**

### CODE REVIEW

**Comment by timarney** [comment]
BTW there's some utility methods that might be of interest to you see ( getLoader, getBabelLoader, injectBabelPlugin, compose) https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/index.js

**Comment by lnhrdt** [comment]
Thanks for the tips! I started out using `getLoader` but wanted to do some higher level things like

> find the file-loader and wherever it is, insert this new loader before it

so I ended up writing those helper functions that you're looking at. Any thoughts on if other rewire writers are approaching the problem the same way and if there's a better approach? Opportunity to expand the utility methods?

**Comment by lnhrdt** [comment]
Abstractly, it was also really hard for me to decide if a given part of the configuration was a "rule" or a "loader". Based on Webpack's [module.loaders is now module.rules](https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules), my understanding is that the dependency (e.g. css-loader) is a loader, but any part of the configuration object (e.g. `{test: /\.css$/, options: {}}`) is a rule. Maybe it would more conventional and easier for others to reason through if we considered renaming `getLoader` to `getRule`, `getRuleMatching`, or something else. Or am I missing something?

Also wanted to say react-app-rewired is a great tool and easy to contribute to. I think that's a sign that you got something right. I tried contributing to https://github.com/kitze/custom-react-scripts earlier this year but couldn't figure out what anything in the codebase did and I gave up. Thanks @timarney!

**Comment by lnhrdt** [comment]
I moved the conversation to a new issue: #127.

**Comment by timarney** [comment]
Perfect & thanks (there's been some nice contributions to make it better over time) - The utility methods are fairly new so we'll still need to figure out if more should be added + naming we'll pick that up on the other thread you created.

**Pull request merged**
