### PR TITLE
Respect Node_path to get the scriptVersionDir

### PR DESCRIPTION
**Pull request by hassanbazzi**

### CODE REVIEW

**Comment by svicalifornia** [comment]
react-app-rewired is failing for me since this commit was added. I am using NVM, which is setting my `NODE_PATH` to its global `lib` directory. My react-scripts are stored in a local `node_modules` directory, which is now being ignored by react-app-rewired, since this commit forces it to use `NODE_PATH` instead.

Furthermore, `NODE_PATH` may be a colon-delimited list of paths. This commit uses `path.join` to concatenate `NODE_PATH` with a relative directory, which won't work if `NODE_PATH` contains more than one path.

This commit should be reverted, and version 1.0.4 should be removed or replaced.

**Comment by svicalifornia** [comment]
$ react-app-rewired start

    module.js:338
        throw err;
        ^

    Error: Cannot find module '<NVM global node-modules path>/react-scripts/config/webpack.config.dev'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (./node_modules/react-app-rewired/scripts/start.js:16:16)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:475:10)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! start: `react-app-rewired start`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     ....

**Comment by svicalifornia** [comment]
Since the `NODE_PATH` can be set to any number of paths, it is not a reliable way to specify where react-app-rewired should look for react-scripts and other modules. In place of this commit, I would propose a command-line option to specify such a path. @hassanbazzi can pass his `NODE_PATH` to that option instead.

**Comment by timarney** [comment]
@svicalifornia thanks for letting me know - 1.0.5 is published with the revert - 1.0.4 has been marked as deprecate per npm note as far as removing i.e. use deprecate if your intent is to encourage users to upgrade.

**Comment by svicalifornia** [comment]
Thanks @timarney.

@hassanbazzi What do you think about making a command-line option to add include path(s)? Maybe I can help with that, but I won't be able to do it right away.

**Pull request merged**
