### PR TITLE
updated logo

### PR DESCRIPTION
**Pull request by harrysolovay**
I love your scripts and thought I'd take a shot at fixing that "add poorly designed logo" commit 🥇 

Feel free to tell me that my attempt at a logo is trash haha. Or better yet, provide comments on what you'd like it to be. I'm more than happy to make some revisions 👍

### CODE REVIEW

**Comment by timarney** [comment]
Thanks for your contribution.

Looks a little busy to me but heading in the right direction.  Can you try with less lines?

**Comment by harrysolovay** [comment]
Just pushed a new version of the logo. Let me know what you think :)

**Comment by timarney** [comment]
Liking this - going to merge.

**Comment by harrysolovay** [comment]
👍👍👍

**Pull request merged**
