### PR TITLE
Add react-app-rewire-favicons-plugin

### PR DESCRIPTION
**Pull request by RickyCook**

### CODE REVIEW

**Comment by timarney** [comment]
I seem to get a 404 on your link

https://github.com/rickycook/react-app-rewire-favicons-plugin

**Comment by RickyCook** [comment]
sorry! i saw this when you posted and forgot about it. would you reopen if i updated the link tomorrow morning?

**Comment by timarney** [comment]
@RickyCook feel free update and we'll get that merged in.

**Comment by RickyCook** [comment]
helps if i actually create the repo.... should be fixed now :)

**Comment by RickyCook** [comment]
thanks!

**Comment by timarney** [comment]
Sure thing - I haven't seen the favicons-webpack-plugin before looks handy.

**Comment by RickyCook** [comment]
it's great!

logo in svg? fine; generates browser favicons in different sizes, along with (many) ios/android images for the "add to home screen" features. it's pretty neat!

**Comment by timarney** [comment]
Nice - you happen to be on twitter? Going to tweet that out.

**Comment by RickyCook** [comment]
i am! thatpandadev... but it's not my plugin; i just wrote the rewire part! :P

**Comment by timarney** [comment]
I know - https://twitter.com/timarney/status/999438815763759104

**Comment by RickyCook** [comment]
oh right! thanks ^.^ so much yay for open source right? :D

**Pull request merged**
