### PR TITLE
Allowing customization of where config-overrides.js exists

### PR DESCRIPTION
**Pull request by harrysolovay**
Hi again :) I figured it might be helpful to be able to move config-overrides.js into different parts of a react-app-rewired project. I created a series of useful defaults for my projects and threw them into a single override (then published that override to NPM). This way I can easily configure my apps with just two installations (react-app-rewired and [ideal-rewires](https://github.com/harrysolovay/ideal-rewires)). Then, I specify the config-overrides path in package.json and voila! Simplifies the root directory and decreases setup time.

### CODE REVIEW

**Comment by harrysolovay** [comment]
Hi Tim,

Anything that I should change in this PR?

I think this feature would help clean up some users' DX, and I'd love your feedback. I found [another bundle of rewires](https://github.com/parity-js/parity-react-app/tree/master/packages/react-app-rewire-parity) that users could easily specify in their `package.json`... there's not always a need to write out a custom rewired config.

Please let me know what you think :) Thanks!

Kind regards,

Harry

**Comment by timarney** [comment]
Will take a look when I can.

**Comment by timarney** [comment]
Thinking you could already do this:

https://github.com/timarney/react-app-rewired#3-specify-config-overrides-as-a-directory

```
const { paths } = require('react-app-rewired')
const overrides = require('react-app-rewired/config-overrides')
const config = require(paths.scriptVersion + '/config/webpack.config.dev')

module.exports = overrides.webpack(config, process.env.NODE_ENV)
```

**Comment by harrysolovay** [comment]
With that approach, users still need to create the extra item in their root directory. It also requires 4 lines of JS vs. 1 line in their package.json. It would reduce clutter in users' projects, and allow them to more seamlessly point to a preset. Not to mention, it would allow them to rename their overrides to whatever they want. Is there an implimention that you think would be better?

**Comment by harrysolovay** [comment]
I just pushed [an example repo](https://github.com/harrysolovay/rewire-custom-path-example). This example points to a rewire in `~/config`, which implements a custom ESLint config and [babel-plugin-react-require](https://github.com/vslinko/babel-plugin-react-require). I wasn't able to install my fork as a dependency (monorepo problems?), so I just copy & pasted the 4 new lines within the react-app-rewired node module (you'll need to do the same to get it working). You can swap out `react-app-rewired/packages/react-app-rewired/scripts/utils/paths` with [this file](https://github.com/harrysolovay/react-app-rewired/blob/master/packages/react-app-rewired/scripts/utils/paths.js). Let me know whatcha think 👍

**Comment by timarney** [comment]
Merged this but running into npm publish issues.  Stay tuned.

**Comment by harrysolovay** [comment]
B E A U T I U F U L !!!

**Pull request merged**
